# Generated by Django 3.2.6 on 2021-08-08 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
