# Generated by Django 3.2.6 on 2021-08-27 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_articles_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='long_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
