# Generated by Django 3.2.6 on 2021-08-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
