# Generated by Django 3.2.6 on 2021-10-10 12:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
